language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "tip"

sudo: false

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./...

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload.'
